#include "panel/panel.h"

#include <stdlib.h>
#include <string.h>

#include "panel/panel_internal.h"   // the ownership seam the properties layer uses

#include "annotation/definition.h"
#include "annotation/overview.h"

;;DEFINITION
/**
 * ============================================================================
 * DEFINITION: Panel (panel/panel.c)
 * ============================================================================
 * THE PANEL — the wrapper around one graphvex Element (the visual: geometry +
 * paint). The Element is pure data; the Panel is the thing an app and the input
 * layer talk to. One Panel owns exactly one Element for its whole life.
 *
 * Ownership is a TREE over wrappers: a parent Panel owns the child wrappers it
 * was given, and destroying it frees them (and their Elements) recursively. A
 * child also records its parent so a detach can find its way back; that link is
 * the seam properties/remove.c uses. Wrappers never alias: unlike a bound
 * (Property), each Panel is its own interface identity.
 *
 * This file is ONLY the widget: construction, teardown, its own accessors, and
 * the ownership seam. Operations that read across classes (add, remove,
 * set_location, ...) live in properties/ so no widget file becomes a pile of
 * ops.
 * ============================================================================
 */

;;OVERVIEW
/**
 * ============================================================================
 * CLASS: Panel (panel/panel.c)
 * ============================================================================
 * Wrapper over a graphvex Element, with an owned set of child wrappers.
 *
 * STRUCT FIELDS:
 * ----------------------------------------------------------------------------
 *   Element      *graphics;   // the attached Element (owned; freed on destroy)
 *   struct Panel *parent;     // owning wrapper, or NULL at a root
 *   struct Panel **owned;     // child wrappers (flat; Element tree is separate)
 *   int           ownedCount; // live child wrappers
 *   int           ownedCap;   // allocated slots in `owned`
 *
 * PRIVATE HELPERS:
 * ----------------------------------------------------------------------------
 *   panel_freeWrapper(p) : free a wrapper subtree (Elements freed once by root)
 *
 * FUNCTION REGISTRY (exported by panel/panel.h):
 * ----------------------------------------------------------------------------
 * Constructors:
 *   - Panel_0 / Panel_1 / Panel_2, and the Panel(...) arity chooser
 * Core / tree:
 *   - Panel_destroy, Panel_graphics, Panel_childCount, Panel_childElement,
 *     Panel_parent
 * Ownership seam (panel/panel_internal.h — called by properties/):
 *   - Panel_ownChild, Panel_disownChild
 * Geometry / visual setters:
 *   - Panel_setOffset, setAnchor, setPivot, setTag,
 *     setRadius, setBackground, setBorder, setShadow, setShadowColor,
 *     setVisible
 * Queries:
 *   - Panel_width, height, radius, anchor, pivot, tag, isVisible
 * Events:
 *   - Panel_add<Kind>Event (generated by IMPLEMENT_EVENTS; see event_invoke.h)
 *
 * Operations that live OUTSIDE this widget (properties/):
 *   - Panel_add(...), Panel_remove(...), Panel_setLocation(...),
 *     Panel_setSize(...), Panel_setCornerRadius(...)
 * ============================================================================
 */

struct Panel {
    Element *graphics;      // the attached Element (owned)
    struct Panel *parent;   // the wrapper that owns this one (nullable at a root)
    struct Panel **owned;   // child wrappers this panel owns (flat, descendants included)
    int ownedCount, ownedCap;
};

Panel *Panel_0(void) { return Panel_1(nullptr); }

Panel *Panel_1(const ElementDesc *desc) {
    Panel *p = calloc(1, sizeof *p);
    if (!p) return nullptr;
    (*p).graphics = Element(desc);
    if (!(*p).graphics) { free(p); return nullptr; }
    return p;
}

Panel *Panel_2(float width, float height) {
    ElementDesc d = {0};
    d.width = width;
    d.height = height;
    return Panel_1(&d);
}

// A child wrapper is owned by its parent. Free wrappers recursively; the
// Element tree is freed exactly once by the root's Panel_destroy.
static void panel_freeWrapper(Panel *panel) {
    for (int i = 0; i < (*panel).ownedCount; i++) panel_freeWrapper((*panel).owned[i]);
    free((*panel).owned);
    free(panel);
}

void Panel_destroy(Panel *panel) {
    if (!panel) return;
    if ((*panel).parent) Panel_disownChild((*panel).parent, panel);   // never leave a dangling slot
    for (int i = 0; i < (*panel).ownedCount; i++) panel_freeWrapper((*panel).owned[i]);
    free((*panel).owned);
    Element_destroy((*panel).graphics);   // the Element tree, once
    free(panel);
}

Element *Panel_graphics(const Panel *panel) {
    return panel ? (*panel).graphics : nullptr;
}

// ── the ownership seam (called by properties/add.c, properties/remove.c) ────
void Panel_ownChild(Panel *parent, Panel *child) {
    if (!parent || !child) return;
    if ((*parent).ownedCount == (*parent).ownedCap) {
        int cap = (*parent).ownedCap ? (*parent).ownedCap * 2 : 4;
        struct Panel **grown = realloc((*parent).owned, (size_t)cap * sizeof *grown);
        if (!grown) return;
        (*parent).owned = grown;
        (*parent).ownedCap = cap;
    }
    (*parent).owned[(*parent).ownedCount++] = child;
    (*child).parent = parent;
}

bool Panel_disownChild(Panel *parent, Panel *child) {
    if (!parent || !child) return false;
    for (int i = 0; i < (*parent).ownedCount; i++) {
        if ((*parent).owned[i] != child) continue;
        memmove(&(*parent).owned[i], &(*parent).owned[i + 1],
                (size_t)((*parent).ownedCount - i - 1) * sizeof *(*parent).owned);
        (*parent).ownedCount--;
        (*child).parent = nullptr;
        return true;
    }
    return false;
}

int Panel_childCount(const Panel *panel) {
    return panel ? Element_count((*panel).graphics) : 0;
}

Element *Panel_childElement(const Panel *panel, int index) {
    return panel ? Element_child((*panel).graphics, index) : nullptr;
}

// ── geometry ────────────────────────────────────────────────────────────────
// Panel_setSize is in properties/set_size.c (grouped by property).
void Panel_setOffset(Panel *panel, float x, float y) {
    if (panel) Element_setOffset((*panel).graphics, x, y);
}
void Panel_setAnchor(Panel *panel, int anchor) {
    if (panel) Element_setAnchor((*panel).graphics, anchor);
}
void Panel_setPivot(Panel *panel, int pivot) {
    if (panel) Element_setPivot((*panel).graphics, pivot);
}
void Panel_setTag(Panel *panel, const char *tag) {
    if (panel) Element_setTag((*panel).graphics, tag);
}

// ── visual ──────────────────────────────────────────────────────────────────
void Panel_setRadius(Panel *panel, float radius) {
    if (panel) Element_setRadius((*panel).graphics, radius);
}
void Panel_setBackground(Panel *panel, Color color) {
    if (panel) Element_setBackground((*panel).graphics, color);
}
void Panel_setBorder(Panel *panel, Color color, float width) {
    if (panel) Element_setBorder((*panel).graphics, color, width);
}
void Panel_setShadow(Panel *panel, float offsetX, float offsetY, float blur) {
    if (panel) Element_setShadow((*panel).graphics, offsetX, offsetY, blur);
}
void Panel_setShadowColor(Panel *panel, Color color) {
    if (panel) Element_setShadowColor((*panel).graphics, color);
}
void Panel_setVisible(Panel *panel, bool visible) {
    if (panel) Element_setVisible((*panel).graphics, visible);
}

// ── queries ─────────────────────────────────────────────────────────────────
float Panel_width(const Panel *panel) { return panel ? Element_width((*panel).graphics) : 0.0f; }
float Panel_height(const Panel *panel) { return panel ? Element_height((*panel).graphics) : 0.0f; }
float Panel_radius(const Panel *panel) { return panel ? Element_radius((*panel).graphics) : 0.0f; }
int Panel_anchor(const Panel *panel) { return panel ? Element_anchor((*panel).graphics) : 0; }
int Panel_pivot(const Panel *panel) { return panel ? Element_pivot((*panel).graphics) : 0; }
const char *Panel_tag(const Panel *panel) { return panel ? Element_tag((*panel).graphics) : nullptr; }
bool Panel_isVisible(const Panel *panel) { return panel ? Element_isVisible((*panel).graphics) : false; }
Panel *Panel_parent(const Panel *panel) { return panel ? (*panel).parent : nullptr; }

// ── events ──────────────────────────────────────────────────────────────────
// The `##` IS the class: these become Panel_addMouseEvent, Panel_addScrollEvent,
// Panel_addZoomEvent, Panel_addKeyEvent, Panel_addTouchEvent, Panel_addDocumentEvent.
IMPLEMENT_EVENTS(Panel)
